# -*- coding: utf-8 -*-
"""Copia de Analisis1_ROBERTO CHACON RANGEL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ORsu1X4faLv5w4z0oPXftDnkZbXCXm6C

# **Actividad 2 – Ciencia de Datos para la Toma de Decisiones Estratégicas**

**Título:**
Análisis exploratorio del riesgo de mora en TuCréditoCo mediante técnicas de ciencia de datos

**Autor:**
Roberto Chacón Rangel

**Fecha:**
2026

**Introducción**

La empresa TuCréditoCo enfrenta una crisis financiera debido al incremento de clientes en mora y la disminución de ingresos derivados del pago oportuno de créditos. Por esta razón, se realizó un análisis exploratorio de datos utilizando Python y Google Colab con el objetivo de identificar patrones de riesgo y posibles causas asociadas al incumplimiento de pago de los clientes.

A partir del análisis de variables relacionadas con ingresos, oficinas, edad, tipo de ingreso y valor de los créditos, se busca identificar elementos que permitan mejorar la toma de decisiones estratégicas dentro de la organización.
"""

from google.colab import drive
drive.mount('/content/drive')

ruta1="/content/solicitud_creditos_info.csv"

ruta2="/content/Employees.csv"

import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

import warnings

warnings.filterwarnings('ignore')

dfSolicitudes = pd.read_csv(ruta1) # Carga los datos a la memoria
print(dfSolicitudes.info()) # Comentario: muestra la información general de la tabla de datos
dfSolicitudes.head() # Muestra las primeras filas de la tabla de datos

dfSolicitudes.describe(include='all')

# Frecuencias de la variable default
dfSolicitudes['default'].value_counts()

dfempleados = pd.read_csv(ruta2) # Carga los datos a la memoria
print(dfempleados.info()) # Comentario: muestra la información general de la tabla de datos
dfempleados.head()

# ==============================
# UNIR LOS DOS DATASET
# ==============================

dfunido = dfSolicitudes.merge(
    dfempleados,
    on='Employee',
    how='left'
)

print(f"Dimensiones del dataset unido: {dfunido.shape[0]:,} filas x {dfunido.shape[1]} columnas")

print(f"Valores faltantes en Employee: {dfSolicitudes['Employee'].isna().sum()}")

# Variables relacionadas con empleados
for col in [
    'Employee',
    'employee_age',
    'employe_gender',
    'exp_previa',
    'employee_estudios',
    'resul_prub_seleccion',
    'eval_jefeRH'
]:
    print(f" * {col}")

# Validar que el merge quedó correcto
display(
    dfunido[
        [
            'Employee',
            'employee_age',
            'employe_gender',
            'employee_estudios'
        ]
    ].head()
)

"""MORA GENERAL"""

mora_general = dfSolicitudes['default'].mean() * 100

print(f"Mora general: {mora_general:.2f}%")

"""**GRÁFICO MORA GENERAL**"""

mora = dfSolicitudes['default'].value_counts()

plt.figure(figsize=(6,4))

mora.plot(kind='bar')

plt.title('Clientes en Mora vs No Mora')
plt.xlabel('Default')
plt.ylabel('Cantidad')

plt.show()

"""**MORA POR OFICINA**"""

mora_oficina = dfSolicitudes.groupby('Office')['default'].mean() * 100

mora_oficina = mora_oficina.sort_values(ascending=False)

display(mora_oficina.head(10))

top_oficinas = mora_oficina.head(10)

plt.figure(figsize=(10,5))

top_oficinas.plot(kind='bar')

plt.title('Top 10 Oficinas con Mayor Mora')
plt.xlabel('Oficina')
plt.ylabel('% Mora')

plt.show()

"""**RELACIÓN CRÉDITO / INGRESO**"""

dfSolicitudes['ratio_credito_ingreso'] = (
    dfSolicitudes['loan_amount'] / dfSolicitudes['total_income']
)

dfSolicitudes['ratio_credito_ingreso'].describe()

plt.figure(figsize=(8,5))

plt.hist(
    dfSolicitudes['ratio_credito_ingreso'].dropna(),
    bins=30
)

plt.title('Relación Crédito / Ingreso')
plt.xlabel('Ratio Crédito / Ingreso')
plt.ylabel('Frecuencia')

plt.grid(axis='y', linestyle='--', alpha=0.5)

plt.show()

"""**MORA POR TIPO DE INGRESO**"""

mora_ingreso = dfSolicitudes.groupby('income_type')['default'].mean() * 100

mora_ingreso = mora_ingreso.sort_values(ascending=False)

display(mora_ingreso)

"""**EDAD DE CLIENTE MOROSOS**"""

# Clientes en mora
clientes_mora = dfSolicitudes[dfSolicitudes['default'] == 1]

# Gráfico corregido
plt.figure(figsize=(8,5))

plt.hist(
    clientes_mora['age_years'].dropna(),
    bins=20
)

plt.title('Edad de Clientes en Mora')
plt.xlabel('Edad (años)')
plt.ylabel('Cantidad')

plt.show()

"""**MATRIZ DE CORRELACION**"""

numericas = dfSolicitudes.select_dtypes(include='number')

correlacion = numericas.corr()

plt.figure(figsize=(12,8))

plt.imshow(correlacion, aspect='auto')

plt.colorbar()

plt.xticks(range(len(correlacion.columns)), correlacion.columns, rotation=90)
plt.yticks(range(len(correlacion.columns)), correlacion.columns)

plt.title('Matriz de Correlación')

plt.show()

# Convertir edad de días a años
dfSolicitudes['age_years'] = abs(dfSolicitudes['age']) / 365

# Gráfico corregido
plt.figure(figsize=(8,5))

plt.hist(
    dfSolicitudes['age_years'].dropna(),
    bins=25
)

plt.title('Distribución de Edad de los Clientes')
plt.xlabel('Edad (años)')
plt.ylabel('Cantidad')

plt.show()

plt.figure(figsize=(8,5))

plt.hist(dfSolicitudes['loan_amount'].dropna(), bins=30)

plt.title('Distribución del Valor de los Créditos')
plt.xlabel('Monto del crédito')
plt.ylabel('Cantidad')

plt.show()

# Limitar valores extremos usando percentil 99
limite = dfSolicitudes['total_income'].quantile(0.99)

ingresos_filtrados = dfSolicitudes[
    dfSolicitudes['total_income'] <= limite
]

plt.figure(figsize=(8,5))

plt.hist(
    ingresos_filtrados['total_income'].dropna(),
    bins=30
)

plt.title('Distribución de Ingresos de los Clientes')
plt.xlabel('Ingresos')
plt.ylabel('Cantidad')

plt.grid(axis='y', linestyle='--', alpha=0.5)

plt.show()

plt.figure(figsize=(8,6))

plt.scatter(
    dfSolicitudes['total_income'],
    dfSolicitudes['loan_amount'],
    alpha=0.3
)

plt.title('Ingresos vs Valor del Crédito')
plt.xlabel('Ingresos')
plt.ylabel('Monto del crédito')

plt.show()

plt.figure(figsize=(8,5))

dfSolicitudes.boxplot(
    column='loan_amount',
    by='default'
)

plt.title('Monto del Crédito según Mora')
plt.suptitle('')

plt.xlabel('Estado de Mora')
plt.ylabel('Monto del crédito')

plt.xticks([1,2], ['No Mora', 'Mora'])

plt.grid(axis='y', linestyle='--', alpha=0.5)

plt.show()

mora_asesor = dfunido.groupby('Employee')['default'].mean() * 100

mora_asesor = mora_asesor.sort_values(ascending=False).head(10)

plt.figure(figsize=(10,5))

colores = [
    'red',
    'orange',
    'gold',
    'green',
    'blue',
    'purple',
    'pink',
    'brown',
    'gray',
    'cyan'
]

mora_asesor.plot(
    kind='bar',
    color=colores
)

plt.title('Top 10 Asesores con Mayor Mora')
plt.xlabel('Asesor')
plt.ylabel('% Mora')

plt.xticks(rotation=0)

plt.grid(axis='y', linestyle='--', alpha=0.5)

plt.show()