# -*- coding: utf-8 -*-
"""prueba.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1au1sPERr_wG1A1BnM0LOeG5hJBqra56N
"""

#Declaracion de variables en python
nombre='Roslay Maryeline Bautista Delgado'

print(type(nombre))

numero=23
es_Mujer=True
decimal= 34.7

#estructura de datos
lista=["arroz","huevos","leche"]
conjunto={"limon","manzana"}
diccionario={"Nombre":"Roslay",
             "e-mail": "rm@algo.com"
             }
tupla=("pan","huevos","chocolate")

print(type(lista))
print(type(conjunto))
print(type(diccionario))
print(type(tupla))

#condicionales
if numero > 40:
  print("el numero es mayor a 40")
elif numero == 40:
  print("el numero es igual a 40")
else:
  print("el numero es menor que 40")

#ciclos o bucles
#WHILE
num=1
while num < 10:
  print(num)
  num= num+1

#ciclo for
for i in range(2,10,2):
  print(i)

lavarCarro=True
lavarBaño=False

if lavarCarro | lavarBaño:
  print("te ganaste la boleta")
else:
  print("lo siento no has ganado")

#funciones
def saludar(nombre):
  print("hola",nombre)

saludar("Maryeline")